#!/usr/bin/env python3
"""Generate icons.h for the show_ip C binary from the source PNG files.

Usage:
    python gen_wifi_data.py

Output: build_scripts/buildroot/package/show-ip/src/icons.h

Re-run whenever an icon PNG changes, then commit the updated icons.h.
"""
import os
import sys
from pathlib import Path

try:
    from PIL import Image
except ImportError:
    sys.exit("Pillow not found — run: pip install Pillow")

HERE    = Path(__file__).parent
OUTFILE = HERE / "../../build_scripts/buildroot/package/show-ip/src/icons.h"

ICONS = [
    ("ICON_WIFI_DISCONNECTED", "wifi_disconnected.png"),
    ("ICON_WIFI_1BAR",         "wifi_1bar.png"),
    ("ICON_WIFI_2BAR",         "wifi_2bar.png"),
    ("ICON_WIFI_3BAR",         "wifi_3bar.png"),
    ("ICON_ETH",               "ethernet.png"),
    ("ICON_ETH_DISCONNECTED",  "ethernet_disconnected.png"),
]

SIZE = 25


def load_icon(fname: str) -> bytes:
    img = Image.open(HERE / fname).convert("RGBA")
    assert img.size == (SIZE, SIZE), f"unexpected size {img.size} for {fname}"
    bg = Image.new("RGBA", (SIZE, SIZE), (0, 0, 0, 255))
    bg.paste(img, mask=img.split()[3])
    return bg.convert("RGB").tobytes()


def format_c_array(name: str, data: bytes) -> str:
    lines = [f"static const uint8_t {name}[{SIZE} * {SIZE} * 3] = {{"]
    row_bytes = SIZE * 3
    for row in range(SIZE):
        chunk = data[row * row_bytes: (row + 1) * row_bytes]
        hex_vals = ", ".join(f"0x{b:02X}" for b in chunk)
        lines.append(f"    {hex_vals},")
    lines[-1] = lines[-1].rstrip(",")  # remove trailing comma from last entry
    lines.append("};")
    return "\n".join(lines)


def main():
    out = OUTFILE.resolve()
    out.parent.mkdir(parents=True, exist_ok=True)

    header_lines = [
        "/* icons.h — auto-generated by device_files/images/gen_wifi_data.py",
        " * Re-run that script after changing any icon PNG, then commit this file.",
        " */",
        "#pragma once",
        "#include <stdint.h>",
        "",
        f"#define ICON_SIZE {SIZE}",
        "",
    ]

    for cname, fname in ICONS:
        print(f"  {fname} -> {cname}")
        rgb = load_icon(fname)
        header_lines.append(format_c_array(cname, rgb))
        header_lines.append("")

    out.write_text("\n".join(header_lines), encoding="utf-8")
    print(f"Written: {out}")


if __name__ == "__main__":
    main()
